### ISSUE TITLE
No integration to find

### ISSUE THREAD

**Issue by dinkel1975** [NECH2004/smartmeter_austria#5]
## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1406
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.6 GB
disk_used | 9.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), File editor (5.8.0), Grafana (9.2.0), Node-RED (17.0.10), Samba share (12.3.1), Cloudflared (5.1.6), Mosquitto broker (6.4.0), Zigbee2MQTT (1.36.0-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 18
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9. März 2024 um 07:54
-- | --
current_recorder_run | 19. März 2024 um 14:48
estimated_db_size | 371.43 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have copied as you described but I don´t find the smart_meter_austria integration.
Can you help me?

### Reproduction steps

1.copy zip to folder
2.
3.
...

### Debug logs

```text
nothing
```

**Comment by dinkel1975** [comment]
My fault! I have copied the wrong files!
It works!

**Comment by NECH2004** [comment]
nothing to do.
